"use client";
import Link from "next/link";
import {motion} from "framer-motion";
const reveal={initial:{opacity:0,y:40},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.7}};
export default function Footer({compact=false}:{compact?:boolean}){return <footer className={`mix-footer${compact?" compact-footer":""}`}><motion.div {...(compact?{}:reveal)} className="footer-shell">
  <div className="footer-cta"><p className="section-kicker">[ Start a conversation ]</p><h2>Starting a new project and think we&apos;re the right fit?</h2><Link href="/contact" className="footer-talk"><span>Let&apos;s Talk</span><i>↗</i></Link></div>
  <div className="footer-main"><div><Link className="footer-logo" href="/"><i>DS</i><span><b>DEVILSALES</b><small>WEB STUDIO · USA</small></span></Link><p>Strategy, design and development for ambitious service businesses across the United States.</p><div className="footer-socials"><a href="https://www.facebook.com/profile.php?id=61589616998618" target="_blank" rel="noopener noreferrer" aria-label="Follow DevilSales on Facebook"><span className="social-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M14 8h3V4h-3c-3.3 0-5 2-5 5v2H6v4h3v7h4v-7h3.2l.8-4h-4V9c0-.7.3-1 1-1Z"/></svg></span><span>Facebook</span></a><a href="https://www.instagram.com/devilsales_web?igsh=MnIyMXBjc284NTVw&utm_source=qr" target="_blank" rel="noopener noreferrer" aria-label="Follow DevilSales on Instagram"><span className="social-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.4" cy="6.7" r="1" className="social-dot"/></svg></span><span>Instagram</span></a></div></div><div><h3>Pages</h3><Link href="/">Home</Link><Link href="/#services">Services</Link><Link href="/work">Portfolio</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></div><div><h3>Contact</h3><a href="mailto:info@devilsales.dev">info@devilsales.dev</a><a href="tel:+13155478952">315-547-8952</a><p>Serving businesses across the USA</p></div></div>
  <div className="footer-bottom"><span>© 2026 DevilSales Web</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/sms-policy">SMS</Link></div><span>Built for serious growth.</span></div>
 </motion.div></footer>}
